# Generated by Django 2.2.7 on 2019-12-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armazenamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmazenamentoEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'armazenamento entrada',
                'verbose_name_plural': 'armazenamento entrada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('armazenamento.armazenamento',),
        ),
        migrations.CreateModel(
            name='ArmazenamentoSaida',
            fields=[
            ],
            options={
                'verbose_name': 'armazenamento saida',
                'verbose_name_plural': 'armazenamento saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('armazenamento.armazenamento',),
        ),
        migrations.AlterField(
            model_name='armazenamentoitens',
            name='armazenamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armazenamentos', to='armazenamento.Armazenamento'),
        ),
    ]
